version: ~> 1.0 # needed for imports
import: scala/scala-dev:travis/default.yml

dist: xenial  # GPG stuff breaks on bionic; scala/scala-dev#764
language: scala

stages:
  - name: build

jobs:
  include:
    - stage: build
      if: type != pull_request AND repo = scala/scala AND branch = 2.13.x
      name: publish (bootstrapped) to scala-integration or sonatype
      script:
        # see comment in `bootstrap_fun` for details on the procedure
        # env available in each stage
        #  - by travis config (see below): secret env vars
        #  - by `common` script: WORKSPACE, IVY2_DIR, SBT_CMD, integrationRepoUrl
        #  - by `bootstrap_fun`: publishPrivateTask, ...
        - set -e
        - (cd admin && ./init.sh)
        - source scripts/common
        - source scripts/bootstrap_fun
        - determineScalaVersion
        - removeExistingBuilds $integrationRepoUrl
        - if [ ! -z "$STARR_REF" ]; then buildStarr; fi
        - buildLocker
        - buildQuick
        - triggerScalaDist

    - stage: build
      if: type != pull_request AND repo = scala/scala AND branch = 2.13.x
      name: language spec
      dist: focal
      language: ruby
      rvm: 2.7
      install:
        - ruby -v
        - gem install bundler -v "< 2.5" #scala-dev#857
        - bundler --version
        - bundle install --path vendor/bundle
        # https://travis-ci.community/t/travis-focal-ubuntu-image-uses-now-expired-mongodb-4-4-package/14293/3
        - wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
        # cribbed from https://github.com/SebastiaanKlippert/go-wkhtmltopdf/blob/master/.travis.yml
        - sudo apt-get update
        - sudo apt-get install -y build-essential xorg xfonts-75dpi libpng16-16 libssl1.1
        - wget --quiet "https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb"
        - sudo dpkg -i "wkhtmltox_0.12.6-1.bionic_amd64.deb"
        - rm "wkhtmltox_0.12.6-1.bionic_amd64.deb"
      script:
        - set -e
        - (cd admin && ./init.sh)
        - bundle exec jekyll build -s spec/ -d build/spec
        - export JEKYLL_ENV=spec-pdf
        - bundle exec jekyll build -s spec/ -d build/spec-pdf
        - ./scripts/generate-spec-pdf.sh
      after_success:
        - ./scripts/travis-publish-spec.sh

env:
  global:
    - ADOPTOPENJDK=8
    - secure: "P8EqpZoin/YTnwel9TTxSSAHtXfZ4M262BKXlYUZmjoQsjyvXDAeZ7yAqgAvX5BeRFrGkBToPiE+V60stdWkPKs3+9COw2BDUB1CULBHhRY9Lxordmz0xVhgEfsoH4f6r6wOlIQ9kuaWhmP+JdB/mzOHZhLch9ziPi8O46Z8t4k=" # PRIV_KEY_SECRET, for scripts/travis-publish-spec.sh
    - secure: "T1fxtvLTxioyXJYiC/zVYdNYsBOt+0Piw+xE04rB1pzeKahm9+G2mISdcAyqv6/vze9eIJt6jNHHpKX32/Z3Cs1/Ruha4m3k+jblj3S0SbxV6ht2ieJXLT5WoUPFRrU68KXI8wqUadXpjxeJJV53qF2FC4lhfMUsw1IwwMhdaE8=" # PRIVATE_REPO_PASS, for publishing to scala-ci Artifactory
    - secure: "dbAvl6KEuLwZ0MVQPZihFsPzCdiLbX0EFk3so+hcfEbksrmLQ1tn4X5ZM7Wy1UDR8uN9lxngEwHch7a7lKqpugzmXMew9Wnikr9WBWbJT77Z+XJ/jHI6YuiCRpRo+nvxXGp9Ry80tSIgx5eju0J83IaJL41BWlBkvyAd7YAHORI=" # GPG_SUBKEY_SECRET, so we can sign JARs
    - secure: "RTyzS6nUgthupw5M0fPwTlcOym1sWgBo8eXYepB2xGiQnRu4g583BGuNBW1UZ3vIjRETi/UKQ1HtMR+i7D8ptF1cNpomopncVJA1iy7pU2w0MJ0xgIPMuvtkIa3kxocd/AnxAp+UhUad3nC8lDpkvZsUhhyA0fb4iPKipd2b2xY=" # TRAVIS_TOKEN (login with GitHub as SethTisue), for triggering scala-dist job
    - secure: "cxN4KHc4RvSzqXWMypMh65ENMbbQdIV/kiqFtxA76MlRynNtMFa/A5t76EESRyNFlXMSgh6sgrjGVK5ug7iMQZpYc1TtcE7WvBjxwqD+agA0wO2qZujPd5BYU8z25hw00rYAkxtL+R7IkEgDKKmAgfRM2cbLV/B8JUikWTnRJ2g=" # SONA_USER, token username for publishing to Sonatype
    - secure: "agM/qNyKzAV94JLsZoZjiR2Kd4g+Fr/mbpR2wD84m8vpDGk+pqFflaonYzjXui/ssL0lJIyGmfWJizwCSE0s9v69IMo7vrKWQ9jLam2OJyBLLs/mIGIH/okl5t8pjUJw4oEOoZ//JZAmplv6bz3gIucgziEWLIQKfBCX/kZffc8=" # SONA_PASS, token password for publishing to Sonatype

# caching for sdkman / sbt / ivy / coursier imported from scala-dev
cache:
  directories:
    - $HOME/.rvm

notifications:
  webhooks: https://scala-ci.typesafe.com/benchq/webhooks/travis
